backend:
  name: github
  repo: mcharb54/double-dealer

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: backroad, label: Backroad }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: writer, label: Writer }
      - { name: body, label: Body, widget: markdown }