backend:
  name: github
  repo: mcharb54/double-dealer

publish_mode: editorial_workflow
display_url: https://www.thedoubledealer.com
media_folder: "/images"
public_folder: "/images/uploads"

collections:
  - name: Articles
    label: Articles
    folder: articles
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: backroad, label: Backroad }
      - { name: date, label: Date, widget: date }
      - {
          name: image,
          label: Image,
          widget: image,
          required: true,
        }
      - { name: title, label: Title }
      - { name: writer, label: Writer }
      - { name: body, label: Body, widget: markdown }

  - name: Fiction
    label: Fiction
    folder: fiction
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: backroad, label: Backroad }
      - { name: date, label: Date, widget: date }
      - {
          name: image,
          label: Image,
          widget: image,
          required: true,
        }
      - { name: title, label: Title }
      - { name: writer, label: Writer }
      - { name: body, label: Body, widget: markdown }
