backend:
  name: github
  repo: mcharb54/double-dealer

publish_mode: editorial_workflow
display_url: https://www.thedoubledealer.com
media_folder: "/static/img"
public_folder: "/img"


collections:
  - name: "fiction"
    label: "Fiction"
    folder: "src/pages/fiction"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "backroad", label: "Backroad", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "cover_image", label: "Cover Image", widget: "image", required: true }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "writer", label: "Writer", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "backroad", label: "Backroad", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "cover_image", label: "Cover Image", widget: "image", required: true }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "writer", label: "Writer", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
